import Script from "next/script";
import "../style/global.css";
import NavBar from "@/components/NavBar";
import { Provider } from "react-redux";
import store from "@/redux/store";
import { MasterWrapper } from "@/utils/MasterWrapper";
export const metadata = {
  // title: "Needaan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        {/* <title>Needaan </title> */}
        <meta
          content="Medcare is a health care website template perfect for any healthcare website. This healthcare Webflow template combines the needs of medical, doctor, medicine, hospital, and clinical templates. It is ideal for creating a professional medical website."
          name="description" />
        <meta content="MedCare - Webflow HTML Website Template" property="og:title" />
        <meta
          content="Medcare is a health care website template perfect for any healthcare website. This healthcare Webflow template combines the needs of medical, doctor, medicine, hospital, and clinical templates. It is ideal for creating a professional medical website."
          property="og:description" />
        <meta content="https://cdn.prod.website-files.com/65c992c37023d69385565acc/65f16188631a7cf790a0cb7b_graph.jpg"
          property="og:image" />
        <meta content="MedCare - Webflow HTML Website Template" property="twitter:title" />
        <meta
          content="Medcare is a health care website template perfect for any healthcare website. This healthcare Webflow template combines the needs of medical, doctor, medicine, hospital, and clinical templates. It is ideal for creating a professional medical website."
          property="twitter:description" />
        <meta content="https://cdn.prod.website-files.com/65c992c37023d69385565acc/65f16188631a7cf790a0cb7b_graph.jpg"
          property="twitter:image" />
        <meta property="og:type" content="website" />
        <meta content="summary_large_image" name="twitter:card" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta content="Webflow" name="generator" />

        {/* This Link For Online Care Css */}
        {/* <link
          href="https://cdn.prod.website-files.com/66e49f98dae3a34da3a9c3cc/css/online-health-care.webflow.cf3734e4b.min.css"
          rel="stylesheet" type="text/css" /> */}
        <link href="https://cdn.prod.website-files.com/65c992c37023d69385565acc/65c9dc31c6aa622c981c7036_favicon_32x32px.png"
          rel="shortcut icon" type="image/x-icon" />
        <link
          href="https://cdn.prod.website-files.com/65c992c37023d69385565acc/65c9dc398a42023d2fd60f43_webclip_256x256px.png"
          rel="apple-touch-icon" />
      </head>
      <body>
        <MasterWrapper>
          <NavBar />
          {children}
        </MasterWrapper>
        <Script src="https://d3e54v103j8qbb.cloudfront.net/js/jquery-3.5.1.min.dc5e7f18c8.js?site=65c992c37023d69385565acc"
          type="text/javascript" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
          crossOrigin="anonymous"></Script>
        <Script src="https://assets-global.website-files.com/65c992c37023d69385565acc/js/webflow.e72dc5e5f.js"
          type="text/javascript"></Script>
        <Script src="https://uploads-ssl.webflow.com/js/webflow.js" type="text/javascript"></Script>


      </body>
    </html>
  );
}
